runtime: nodejs20
 
handlers:
  - url: /
    static_files: src/index.html
    upload: src/index.html
    secure: always
 
  - url: /(.*)
    static_files: src/\1
    upload: src/(.*)
    secure: always